library(shiny)
library(readxl)
library(plotly)
library(ggplot2)
library(reshape2)
library(shinydashboard)
KansasCrimeLong <- read_excel("~/Desktop/KUMC/Fall2021/DATA 824/Final Project/KansasCrimeLong.xlsx")
KCrime <- KansasCrimeLong

KCrimeRe <- reshape(KCrime, idvar = "County", varying = c("2012", "2013", "2014", "2015", "2016", "2017"), 
                    times = c("2012", "2013", "2014", "2015", "2016", "2017"), 
                    new.row.names = 1:1000, v.name = c("Crime Rate"), direction = "long")

colnames(KCrimeRe)[2] <- c("Year")

library(dplyr)
KCrimeRe %>%
  select(County, `Crime Rate`) %>%
  filter(County == "Allen") %>%
  summarise(mean = mean(`Crime Rate`))

KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Anderson")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Atchison")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Barber")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Barton")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Bourbon")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Brown")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Butler")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Chase")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Chautauqua")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Cherokee")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Cheyenne")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Clark")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Clay")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Cloud")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Coffey")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Comanche")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Cowley")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Crawford")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Decatur")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Dickinson")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Doniphan")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Douglas")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Edwards")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Elk")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Ellis")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Ellsworth")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Finney")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Ford")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Franklin")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Geary")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Gove")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Graham")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Grant")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Gray")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Greeley")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Greenwood")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Hamilton")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Harper")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Harvey")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Haskell")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Hodgeman")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Jackson")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Jefferson")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Jewell")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Johnson")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Kearny")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Kingman")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Kiowa")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Labette")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Lane")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Leavenworth")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Lincoln")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Linn")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Logan")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Lyon")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Mcpherson")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Marion")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Marshall")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Meade")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Miami")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Mitchell")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Montgomery")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Morris")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Morton")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Nemaha")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Neosho")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Ness")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Norton")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Osage")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Osborne")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Ottawa")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Pawnee")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Phillips")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Pottawatomie")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Pratt")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Rawlins")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Reno")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Republic")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Rice")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Riley")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Rooks")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Rush")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Russell")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Saline")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Scott")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Sedgwick")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Seward")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Shawnee")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Sheridan")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Sherman")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Smith")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Stafford")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Stanton")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Stevens")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Sumner")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Thomas")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Trego")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Wabaunsee")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Wallace")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Washington")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Wichita")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Wilson")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Woodson")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Wyandotte")%>% summarise(mean = mean(`Crime Rate`))
KCrimeRe %>% select(County, `Crime Rate`) %>% filter(County == "Kansas")%>% summarise(mean = mean(`Crime Rate`))

Mean_Crime_Rates <- read_excel("Desktop/KUMC/Fall2021/DATA 824/Final Project/Mean Crime Rates.xlsx")

Mean_Crime_Rates2 <- Mean_Crime_Rates[order(Mean_Crime_Rates$`Mean Crime Rate`)]

Mean_Crime_Rates2 <- read_excel("Desktop/KUMC/Fall2021/DATA 824/Final Project/Mean Crime Rates2.xlsx")

describe(Mean_Crime_Rates2)

head(Mean_Crime_Rates2, 10)

tail(Mean_Crime_Rates2, 10)

mean(Mean_Crime_Rates2$`Mean Crime Rate`)
